[metadata]
name = dot-live
version = attr: dot.__version__
description = Minimal live SimSwap runner
long_description = file: README.md
long_description_content_type = text/markdown
license = BSD 3-Clause License

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    kornia
    mediapipe>=0.10
    numpy
    opencv-contrib-python
    opencv-python
    Pillow
    psutil>=5.8
    PyYAML
    requests
    scikit-image
    scipy
    torch>=2.0
    torchvision

[options.extras_require]
virtualcam =
    pyvirtualcam
test =
    pytest

[options.packages.find]
where = src
